#define HAVE_ALIGNED_ALLOC 1
#define HAVE_CLOCKID_T 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CLOCK_NANOSLEEP 1
#define HAVE_GETRANDOM 1
#define HAVE_INTTYPES_H 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_REGISTER_T 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define PACKAGE_BUGREPORT "http://rumpkernel.org/"
#define PACKAGE_NAME "rumpuser-posix"
#define PACKAGE_STRING "rumpuser-posix 999"
#define PACKAGE_TARNAME "rumpuser-posix"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "999"
#define STDC_HEADERS 1
