__asm__ (".text\n\t"
	 ".global _start \n\t"
	 "_start:\n\t"
	 "	and	$-16,%esp\n\t"
	 "	sub	$12,%esp\n\t"
	 "	pushl	%ebx\n\t"
	 "	pushl	%ecx\n\t"
	 "	pushl	%edx\n\t"
	 "	call	__platform_init\n\t"
	 "1:	jmp	1b\n\t");
