#define SYS_read                        3
#define SYS_write                       4
#define SYS_kill                        37
#define SYS_ioctl                       54
#define SYS_munmap                      91
#define SYS_fsync                       118
#define SYS_pread64                     179
#define SYS_pwrite64                    180
#define SYS_mmap2                       192
#define SYS_fstat64                     197
#define SYS_exit_group                  234
#define SYS_clock_gettime		246
#define SYS_clock_getres                247
#define SYS_clock_nanosleep             248
#define SYS_getrandom                   359
