#	$NetBSD: Makefile,v 1.9 2014/03/13 18:14:13 pooka Exp $
#

VIRTIF=virt

LIB=	rumpnet_virtif
SRCS=	if_virt.c

VIRTIFDIR:=	${.PARSEDIR}
.PATH:		${VIRTIFDIR}

CPPFLAGS+=	-DVIRTIF_BASE=${VIRTIF} -I${VIRTIFDIR}

RUMPTOP= ${TOPRUMP}

.include "${RUMPTOP}/Makefile.rump"
.include <bsd.lib.mk>
.include <bsd.klinks.mk>
