__asm__ (".weak _init\n\t"
	 ".weak _fini\n\t"
	 ".text\n\t"
	 ".global _start\n\t"
	 "_start:\n\t"
	 "        xor %ebp,%ebp\n\t"
	 "        pop %ecx\n\t"
	 "        mov %esp,%eax\n\t"
	 "        and $-16,%esp\n\t"
	 "        push %esp\n\t"
	 "        push %esp\n\t"
	 "        push %edx\n\t"
	 "        push $_fini\n\t"
	 "        push $_init\n\t"
	 "        push %eax\n\t"
	 "        push %ecx\n\t"
	 "        push $main\n\t"
	 "        call __platform_init\n\t"
	 "1:      jmp 1b\n\t");
